theme: jekyll-theme-minimal
title: "Anubrata Das"
subtitle: "অনুব্রত দাস"
author: "Anubrata"
logo: "/assets/images/Me.jpg"
navigation: 1
about: "#about"
research: "#research"
publication: "#publication"
news: "#news"
