theme: jekyll-theme-minimal
# remote-theme: alshedivat/al-folio
title: "Anubrata Das"
subtitle: "অনুব্রত দাস"
author: "Anubrata"
logo: "/assets/images/pp.jpeg"
email: "anubrata.das[at]utexas.edu"
twitter: "@d_anubrata"
navigation: 1
research: "#research"
publication: "#publications"
news: "#news"
facts: "#fat-reading-group"
talks: "#talks"
