theme: jekyll-theme-minimal
title: "Anubrata Das"
subtitle: "অনুব্রত দাস"
author: "Anubrata"
logo: "/assets/images/Me.jpg"
email: "anubrata[at]utexas.edu"
navigation: 1
about: "#about-me"
research: "#research"
publication: "#publications"
news: "#news"
facts: "#fat-reading-group"
